# Based on the GITLAB Template in the following location:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/LaTeX.gitlab-ci.yml

---
variables:
  LATEX_IMAGE: listx/texlive:2020

pages:
  image: $LATEX_IMAGE
  
  script:
    - latexmk -pdf main.tex
    - mkdir public
    - mv index.html public/index.html
    - mv main.pdf public/main.pdf

  artifacts:
    paths:
      - public

  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH